export enum ErrorCodes {
	AuthAttemptNotPending = 'auth/attempt-not-pending',
	AuthInvalidCredentials = 'auth/invalid-credentials',
	AuthInvalidMfaCode = 'auth/invalid-mfa-code',
	AuthInvalidToken = 'auth/invalid-token',
	AuthUnknownMfaType = 'auth/unknown-mfa',
	CorsNotAllowed = 'cors/not-allowed',
	InvalidQueryParameter = 'query/invalid-parameter-type',
	MissingQueryParameter = 'query/missing-parameter',
	OAuthClientNotFound = 'oauth/client-not-found',
	OAuthInvalidClient = 'oauth/invalid-client',
	OAuthInvalidCodeChallenge = 'oauth/invalid-code-challenge',
	OAuthInvalidRedirect = 'oauth/invalid-redirect-uri',
	OAuthInvalidResponseType = 'oauth/invalid-response-type',
	OAuthInvalidScope = 'oauth/invalid-scope',
	OAuthInvalidState = 'oauth/invalid-state',
	RouteNotFound = 'route/not-found',
	ServerForbidden = 'server/forbidden',
	ServerInternalError = 'server/internal-error',
	UnknownError = 'unknown/error',
}
